spring:
  application:
    name: vp-upload
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:mysql://localhost:3306/hackvp
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

aws:
  region: sa-east-1
  access-key: ${ACCESS_KEY}
  access-secret: ${ACCESS_SECRET}
  s3:
    bucket:
      video: hack-vp-videos